services:
  - type: web
    name: word-crush
    env: node
    buildCommand: >
      npm install &&
      cd client &&
      npm install &&
      mkdir -p src/types &&
      npm run build
    startCommand: npm run render-start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: SKIP_PREFLIGHT_CHECK
        value: "true"
      - key: TSC_COMPILE_ON_ERROR
        value: "true" 